"""init

Revision ID: 0
Revises: 
Create Date: 2022-11-11 14:58:01.904436

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lnk_blacklisted_domain',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('domain_name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('lnk_blacklisted_domain_pkey'))
    )
    op.create_index(op.f('lnk_blacklisted_domain_domain_name_idx'), 'lnk_blacklisted_domain', ['domain_name'], unique=True)
    op.create_table('lnk_url',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('long_url', sa.Text(), nullable=False),
    sa.Column('short_code', sa.String(length=10), nullable=False),
    sa.Column('expired_on', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_accessed_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('ip_address', sa.String(length=16), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('lnk_url_pkey'))
    )
    op.create_index(op.f('lnk_url_short_code_idx'), 'lnk_url', ['short_code'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('lnk_url_short_code_idx'), table_name='lnk_url')
    op.drop_table('lnk_url')
    op.drop_index(op.f('lnk_blacklisted_domain_domain_name_idx'), table_name='lnk_blacklisted_domain')
    op.drop_table('lnk_blacklisted_domain')
    # ### end Alembic commands ###
